@baseUrl = http://localhost:40000
## Mude o token aqui para novos testes:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJtYXJjZWxvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYzMzk2ODAzLCJleHAiOjE3NjM0MDQwMDN9.5SFuzr7a0LAjRGpi5yEIVLQoM5OYQQGIVK75mAs7drk

## TESTE USUARIO/LOGIN ##
################################################
# Criar Usuario
################################################
POST {{baseUrl}}/insertUsuario
Content-Type: application/json

{
  "nome_usuario": "Marcelo",
  "email_usuario": "marcelo@example.com",
  "senha_usuario": "123456",
  "tipo_usuario": "1"
}

################################################
# Logar Usuario
################################################
POST {{baseUrl}}/login
Content-Type: application/json

{
  "UserName": "marcelo@example.com",
  "Password": "123456"
}


################################################
# Atualizar Usuario
################################################
POST {{baseUrl}}/updateUsuario
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "nome_usuario": "Marcelo",
  "email_usuario": "mfavaro54@example.com",
  "senha_usuario": "123456",
  "tipo_usuario": "1",
  "id_usuario": 2
}

################################################
#  Buscar Usuario por ID
################################################
POST {{baseUrl}}/GetUsuarioByID
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_usuario": 2
}

################################################
# Deletar Usuario
################################################
POST {{baseUrl}}/deleteUsuario
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_usuario": 1
}

################################################
#  Logout Usuario
################################################
POST {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

## TESTE CLIENTE ##
################################################
# Criar Cliente
################################################
POST {{baseUrl}}/insertCliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome_cliente": "João da Silva",
  "cpf_cliente": "12345678900",
  "telefone_cliente": "11988887777",
  "email_cliente": "joao.silva@example.com"
}

################################################
# Atualizar Cliente
################################################
POST {{baseUrl}}/updateCliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome_cliente": "João",
  "cpf_cliente": "12345678900",
  "telefone_cliente": "11988887777",
  "email_cliente": "joao.silva@example.com",
  "id_cliente": "1"
}

################################################
# Buscar Cliente por ID
################################################
POST {{baseUrl}}/getClienteById
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_cliente": 1
}

################################################
# Deletar Cliente
################################################
POST {{baseUrl}}/deleteCliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_cliente": 1
}

## TESTE MOTO ##
################################################
#  Criar Moto
################################################
POST {{baseUrl}}/insertMoto
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "modelo_moto": "CB 500F",
  "marca_moto": "Honda",
  "ano_moto": 2021,
  "id_cliente": 1
}

################################################
#  Atualizar Moto
################################################
POST {{baseUrl}}/updateMoto
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "modelo_moto": "CB 500F",
  "marca_moto": "Honda",
  "ano_moto": 2022,
  "id_cliente": 1,
  "id_moto": 1
}

################################################
#  Buscar Moto por ID
################################################
POST {{baseUrl}}/getMotoById
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_moto": 2
}

################################################
#  Deletar Moto 
################################################
POST {{baseUrl}}/deleteMoto
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_moto": 1
}


## TESTE TRATAMENTO ##
################################################
# Criar Tratamento
################################################
POST {{baseUrl}}/InsertTratamento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome_tratamento": "Troca de óleo",
  "valor_tratamento": 150.00,
  "descricao_tratamento": "Troca completa de óleo do motor"
}

################################################
# Atualizar Tratamento
################################################
POST {{baseUrl}}/UpdateTratamento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_tratamento": 1,
  "nome_tratamento": "Troca de óleo premium",
  "valor_tratamento": 200.00,
  "descricao_tratamento": "Troca completa de óleo premium do motor"
}

################################################
# Buscar Tratamento por ID
################################################
POST {{baseUrl}}/GetTratamentoByID
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_tratamento": 1
}

################################################
# Deletar Tratamento
################################################
POST {{baseUrl}}/DeleteTratamento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_tratamento": 1
}

## TESTE MOTO TRATAMENTO ##
################################################
# Criar Moto Tratamento
################################################
POST {{baseUrl}}/InsertMotoTratamento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_moto": 2,
  "id_tratamento": 1
}

################################################
# Atualizar Moto Tratamento
################################################
POST {{baseUrl}}/UpdateMotoTratamento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_moto_tratamento": 1,
  "id_moto": 1,
  "id_tratamento": 2
}

################################################
# Buscar Moto Tratamento por ID
################################################
POST {{baseUrl}}/GetMotoTratamentoByID
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_moto_tratamento": 1
}

################################################
# Deletar Moto Tratamento
################################################
POST {{baseUrl}}/DeleteMotoTratamento
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_moto_tratamento": 1
}