@baseUrl = http://localhost:40000
## Mude o token aqui para novos testes:
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhbjdAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjMzODYxNDcsImV4cCI6MTc2MzM5MzM0N30.1JN9RtIjAAU18cBa_PNwJAr6gtGTxuZMB9eIrnzbrH0


################################################
# Logar Usuario
################################################
POST {{baseUrl}}/login
Content-Type: application/json

{
  "UserName": "an7@example.com",
  "Password": "123456"
}


################################################
# Criar usuário
################################################
POST {{baseUrl}}/insertUsuario
Content-Type: application/json

{
  "nome_usuario": "Marcelo",
  "email_usuario": "an7@example.com",
  "senha_usuario": "123456",
  "tipo_usuario": "1"
}

################################################
#  Buscar usuário por ID
################################################
POST {{baseUrl}}/GetUsuarioByID
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id_usuario": 2
}

################################################
#  Logout usuário
################################################
POST {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{

}